name: pdquadrotor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # You can change this to your desired Python version
  - pip
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - diffusers==0.13.1
      - jax==0.4.23
      - jaxlib==0.4.23
      - huggingface-hub==0.24.6
      - matplotlib==3.5.3